server:
  port: 8081

logging:
  level:
    com.github.binarywang.wxpay: error
    me.chanjar.weixin: error
    com.esiran.greenpay.common.sign: debug
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/greenpay?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: admin888
  redis:
    port: 6379
    host: localhost

greenpay:
  openapi:
    enable_sign: true

wechat:
  app_id: wx2aeda339f56138bf
  app_secret: 731787f51247a33c4ff210cd613dd780
  mch_id: 1519342911
  mch_key: 2624eedd356624bc7a662c29ceb0a20e
  cert_path: classpath:/keystory/wxpay/apiclient_cert.p12

